members/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from .register_member_views import MemberRegistrationWizard
from .dashboard_views import dashboard
from . member_views import view_members,view_transactions,mini_statement_view, mini_statement_form,member_profile
from . import update_member_accounts_views
from  .update_member_accounts_views import search_member
from .import views


app_name = 'members'

urlpatterns = [
    path('', RedirectView.as_view(url='dashboard/', permanent=False)),  # Redirect root to dashboard
    path('admin/', admin.site.urls),
    path('dashboard/', dashboard, name='dashboard'),
    path('view_members/', view_members, name='view_members'),
    path('transactions/', view_transactions, name='transactions'),
    path('mini_statement/', mini_statement_view, name='mini_statement'),
    path('mini_statement_form/', mini_statement_view, name='mini_statement_form'),  # Add this line
    path('search_member/', search_member, name='search_member'),
    path('register_member/', MemberRegistrationWizard.as_view(), name='register_member'),
    path('update_member_accounts/<int:member_id>/', update_member_accounts_views.update_member_accounts, name='update_member_accounts'),
    path('member_details/<int:member_id>/', update_member_accounts_views.member_details, name='member_details'),
    path('select_action/<int:member_id>/', update_member_accounts_views.select_action, name='select_action'),
    path('deposit/<int:member_id>/', update_member_accounts_views.deposit, name='deposit'),
    path('loan-repayment/<int:member_id>/', update_member_accounts_views.loan_repayment, name='loan_repayment'),
    path('withdraw/<int:member_id>/', update_member_accounts_views.withdrawal, name='withdraw'),
    path('transfer/<int:member_id>/', update_member_accounts_views.transfer, name='transfer'),
    path('member_profile/<int:member_id>/', member_profile, name='member_profile'),
    #more urls
    path('edit/', views.search_member_to_edit, name='search_member_1'),
    path('statement/', views.mini_statement_form, name='mini_statement_form'),
    path('report/savings', views.savings_report, name='savings_report'),
    path('report/loans/', views.loans_report, name='loans_report'),
    path('report/share-capital/', views.share_capital_report, name='share_capital_report'),
    path('report/all-accounts/', views.all_accounts_report, name='all_accounts_report'),
    path('edit/personal/<int:member_id>/', views.edit_personal_details, name='edit_personal_details'),
    path('edit/personal', views.edit_personal_details, name='edit_personal_details'),
    path('edit/next-of-kin/', views.edit_next_of_kin, name='edit_next_of_kin'),
    path('edit/register/', views.register_member, name='register_member'),
    path('deactivate/', views.deactivate_member, name='deactivate_member'),
    path('statistics/membership/', views.membership_stats, name='membership_stats'),
    path('statistics/accounts/', views.accounts_stats, name='accounts_stats'),
    path('statistics/joining/', views.member_joining_stats, name='member_joining_stats'),
    path('statistics/dormant/', views.dormant_members, name='dormant_members'),
    path('statistics/deceased/', views.deceased_members, name='deceased_members'),
    path('statistics/top-savers/', views.top_savers, name='top_savers'),
    path('statistics/top-borrowers/', views.top_borrowers, name='top_borrowers'),
    path('statistics/next-of-kin/', views.non_member_next_of_kins, name='non_member_next_of_kins'),
]

saccomis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('sms/', include('sms.urls')),
    path('loans/', include('loans.urls')),
    path('reports/', include('reports.urls')),
    path('groups/', include('groups.urls')),
    path('accounting/', include('accounting.urls')),
    path('registry/', include('registry.urls')),
    path('', include('members.urls', namespace='members')),
]

sms/urls.py
# urls.py in the sms app

from django.urls import path
from . import views

app_name = 'sms'

urlpatterns = [
    path('compose/', views.compose_sms, name='compose_sms'),
    path('view/', views.view_sms, name='view_sms'),
]

members/forms.py
from django import forms
from .models import Member, MemberAccount, NextOfKin

class DepositForm(forms.Form):
    account_type = forms.ChoiceField(choices=[
        ('savings', 'Savings'),
        ('share_capital', 'Share Capital'),
        ('loan', 'Loan Repayment'),
     ])
    external_ref_code = forms.CharField(label='External Reference Code', max_length=100, required=True)
    amount = forms.DecimalField(max_digits=10, decimal_places=2, required=True)
 

def clean_amount(self):
        amount = self.cleaned_data['amount']
        if amount <= 0:
            raise forms.ValidationError("Amount must be greater than zero.")
        return amount

class LoanRepaymentForm(forms.Form):
    amount = forms.DecimalField(max_digits=10, decimal_places=2, label='Repayment Amount')
    external_ref_code = forms.CharField(max_length=50, label='External Reference Code')

    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        if amount <= 0:
            raise forms.ValidationError("Repayment amount must be greater than zero.")
        return amount

class WithdrawalForm(forms.Form):
    amount = forms.DecimalField(max_digits=10, decimal_places=2)
    

class TransferForm(forms.Form):
    transfer_from_account_type = forms.ChoiceField(choices=[
        ('savings', 'Savings'),
        ('share_capital', 'Share Capital'),
        ('loan', 'Loan Repayment'),
     ])
    transfer_to_account_type = forms.ChoiceField(choices=[
        ('savings', 'Savings'),
        ('share_capital', 'Share Capital'),
        ('loan', 'Loan Repayment'),
     ])
    amount = forms.DecimalField(max_digits=10, decimal_places=2)
    recipient_id = forms.IntegerField()

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = [
            'first_name', 'middle_name', 'last_name','member_national_id', 'registration_date', 'phone_number',
            'secondary_phone_number', 'email', 'date_of_birth', 'gender', 'client_type', 
            'client_photo', 'marital_status', 'address', 'town', 'profession', 
            'employment_status', 'employment_income', 'signature', 'spouse_name', 
            'spouse_address'
        ]


class MemberAccountForm(forms.ModelForm):
    external_ref_code = forms.CharField(label='External Reference Code', max_length=100, required=True)

    class Meta:
        model = MemberAccount
        fields = ['share_capital', 'savings', 'reg_fee', 'external_ref_code']


        

class NextOfKinForm(forms.ModelForm):
    class Meta:
        model = NextOfKin
        fields = ['full_name', 'relationship', 'kin_national_id', 'address', 'email', 'phone_number']


class MiniStatementForm(forms.Form):
    member_id = forms.CharField(label='Member ID', max_length=100)
    account_type = forms.ChoiceField(choices=[('savings', 'Savings'), ('share_capital', 'Share Capital'), ('loan', 'Loan Account')], label='Account Type')
    start_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}), label="Start Date")
    end_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}), label="End Date")

members/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Member, MemberAccount, NextOfKin,MemberAccountsLedger
from .forms import MemberForm, NextOfKinForm

@login_required
def search_member_to_edit(request):
    query = request.GET.get('q')
    members = Member.objects.all()

    if query:
        members = members.filter(first_name__icontains=query)
    
    return render(request, 'members/search_member_1.html', {'members': members})

@login_required
def mini_statement_form(request):
    if request.method == 'POST':
        member_id = request.POST.get('member_id')
        member = get_object_or_404(Member, pk=member_id)
        transactions = MemberAccountsLedger.filterobjects.all(member_id=member_id)
        return render(request, 'members/mini_statement.html', {'member': member, 'transactions': transactions})
    
    members = Member.objects.all()
    return render(request, 'members/mini_statement_form.html', {'members': members})

@login_required
def savings_report(request):
    accounts = MemberAccount.objects.all()
    return render(request, 'members/savings_report.html', {'accounts': accounts})

@login_required
def loans_report(request):
    loans = MemberAccount.objects.filter(account_type='savings')
    return render(request, 'members/loans_report.html', {'loans': loans})

@login_required
def share_capital_report(request):
    accounts = MemberAccount.objects.filter(account_type='share_capital')
    return render(request, 'members/share_capital_report.html', {'accounts': accounts})

@login_required
def all_accounts_report(request):
    accounts = MemberAccount.objects.all()
    return render(request, 'members/all_accounts_report.html', {'accounts': accounts})

@login_required
def edit_personal_details(request, member_id):
    member = get_object_or_404(Member, pk=member_id)
    if request.method == 'POST':
        form = MemberForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            messages.success(request, 'Personal details updated successfully!')
            return redirect('members:edit_personal_details', member_id=member.id)
    else:
        form = MemberForm(instance=member)
    return render(request, 'members/edit_personal_details.html', {'form': form})

@login_required
def edit_next_of_kin(request, member_id):
    member = get_object_or_404(Member, pk=member_id)
    next_of_kin = member.nextofkin
    if request.method == 'POST':
        form = NextOfKinForm(request.POST, instance=next_of_kin)
        if form.is_valid():
            form.save()
            messages.success(request, 'Next of kin details updated successfully!')
            return redirect('members:edit_next_of_kin', member_id=member.id)
    else:
        form = NextOfKinForm(instance=next_of_kin)
    return render(request, 'members/edit_next_of_kin.html', {'form': form})

@login_required
def register_member(request):
    if request.method == 'POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Member registered successfully!')
            return redirect('members:register_member')
    else:
        form = MemberForm()
    return render(request, 'members/register_member.html', {'form': form})

@login_required
def deactivate_member(request, member_id):
    member = get_object_or_404(Member, pk=member_id)
    member.is_active = False
    member.save()
    messages.success(request, 'Member deactivated successfully!')
    return redirect('members:deactivate_member')

@login_required
def membership_stats(request):
    active_members = Member.objects.filter(is_active=True).count()
    inactive_members = Member.objects.filter(is_active=False).count()
    return render(request, 'members/membership_stats.html', {
        'active_members': active_members,
        'inactive_members': inactive_members
    })

@login_required
def accounts_stats(request):
    total_savings = MemberAccount.objects.filter(account_type='savings').aggregate(Sum('balance'))['balance__sum']
    total_loans = MemberAccount.objects.filter(account_type='loan').aggregate(Sum('balance'))['balance__sum']
    return render(request, 'members/accounts_stats.html', {
        'total_savings': total_savings,
        'total_loans': total_loans
    })

@login_required
def member_joining_stats(request):
    # Example implementation
    members_joined_last_month = Member.objects.filter(joined_date__month=last_month).count()
    return render(request, 'members/member_joining_stats.html', {
        'members_joined_last_month': members_joined_last_month
    })

@login_required
def dormant_members(request):
    dormant_members = Member.objects.filter(is_active=False)
    return render(request, 'members/dormant_members.html', {'dormant_members': dormant_members})

@login_required
def deceased_members(request):
    deceased_members = Member.objects.filter(status='deceased')
    return render(request, 'members/deceased_members.html', {'deceased_members': deceased_members})

@login_required
def top_savers(request):
    account_type ='savings'
    top_savers = MemberAccount.objects.filter(account_type).order_by('-account_type')[:10]
    return render(request, 'members/top_savers.html', {'top_savers': top_savers})

@login_required
def top_borrowers(request):
    top_borrowers = MemberAccount.objects.filter(account_type='loan').order_by('-balance')[:10]
    return render(request, 'members/top_borrowers.html', {'top_borrowers': top_borrowers})

@login_required
def non_member_next_of_kins(request):
    non_members = NextOfKin.objects.filter(member__isnull=True)
    return render(request, 'members/non_member_next_of_kins.html', {'non_members': non_members})

members/templates/deposit.html
{% extends 'base.html' %}

{% block title %}
    Deposit - AKIBANIPESA
{% endblock %}

{% block content %}
    {% include 'more_menu_members.html' %}
    <div class="container mt-5 p-4" style="background-color: #f8f9fa; border-radius: 8px;">
        <!-- Message display section -->
        {% if messages %}
        <div class="mt-4">
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </div>
        {% endif %}
        <h1 class="text-center mb-4">Deposit for {{ member.first_name }} {{ member.last_name }}</h1>
        <form method="POST" class="bg-white shadow p-4 rounded mx-auto" style="max-width: 500px;">
            {% csrf_token %}
            <div class="form-group">
                <label for="account_type" class="form-label">Account Type</label>
                <select class="form-control" id="account_type" name="account_type">
                    <option value="savings">Savings</option>
                    <option value="share_capital">Share Capital</option>
                   
                </select>
            </div>
            <div class="form-group">
                <label for="amount" class="form-label">Amount</label>
                <input type="text" class="form-control" id="amount" name="amount">
            </div>
            <div class="form-group">
                <label for="external_ref_code" class="form-label">External Reference Code</label>
                <input type="text" class="form-control" id="external_ref_code" name="external_ref_code">
            </div>
            <button type="submit" class="btn btn-primary">Deposit</button>
        </form>
    </div>
{% endblock %}

members/templates/loan_repayment.html
<!-- loan_repayment.html -->

{% extends 'base.html' %}
{% load static %}

{% block title %}
    Loan Repayment - AKIBANIPESA
{% endblock %}

{% block content %}
   {% include 'more_menu_members.html' %}
    <div class="container mx-auto mt-8 px-4 bg-light-gray p-4 rounded shadow">
        <h2 class="text-2xl font-bold mb-4">Loan Repayment</h2>

        <!-- Message display section -->
        {% if messages %}
            <div class="container mt-4">
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <form method="post" class="max-w-md bg-white shadow-md rounded-lg p-6 mx-auto">
            {% csrf_token %}
            <div class="mb-4">
                <label for="amount" class="block text-sm font-medium text-gray-700">Repayment Amount</label>
                <input type="text" class="form-control mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" id="amount" name="amount">
            </div>
            <div class="mb-4">
                <label for="external_ref_code" class="block text-sm font-medium text-gray-700">External Reference Code</label>
                <input type="text" class="form-control mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" id="external_ref_code" name="external_ref_code">
            </div>
            <button type="submit" class="btn btn-primary">Repay Loan</button>
        </form>
    </div>
{% endblock %}

members/templates/member_profile.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
    Member Profile - AKIBANIPESA
{% endblock %}

{% block content %} 
    {% include 'more_menu_members.html' %}
    <div class="container mx-auto mt-8 px-4">
	<div class="text-center mb-8">
            <h1 class="text-3xl font-bold mt-4">{{ member.first_name }} {{ member.last_name }}  Profile</h1>
        </div>
        <div class="text-center mb-8">
            {% if member.client_photo %}
                <img src="{{ member.client_photo.url }}" alt="Member Photo" class="w-48 h-48 object-cover rounded-full mx-auto">
            {% else %}
                <p>No photo found.</p>
            {% endif %}
        </div>
        
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6"> <!-- Adjusted gap-6 for smaller gap -->
            <!-- Personal Details Card -->
            <div class="bg-white shadow-md rounded-lg p-4"> <!-- Adjusted p-4 for smaller padding -->
                <h2 class="text-lg font-semibold mb-2">Personal Details</h2>
                <table class="min-w-full divide-y divide-gray-200">
                    <tbody class="bg-white divide-y divide-gray-200">
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Name:</strong></td>
                            <td class="px-3 py-2">{{ member.first_name }} {{ member.middle_name }} {{ member.last_name }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>National ID:</strong></td>
                            <td class="px-3 py-2">{{ member.member_national_id }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Registration Date:</strong></td>
                            <td class="px-3 py-2">{{ member.registration_date|date:"F d, Y" }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Phone Number:</strong></td>
                            <td class="px-3 py-2">{{ member.phone_number }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Secondary Phone Number:</strong></td>
                            <td class="px-3 py-2">{{ member.secondary_phone_number }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Email:</strong></td>
                            <td class="px-3 py-2">{{ member.email }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Date of Birth:</strong></td>
                            <td class="px-3 py-2">{{ member.date_of_birth|date:"F d, Y" }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Gender:</strong></td>
                            <td class="px-3 py-2">{{ member.gender }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Client Type:</strong></td>
                            <td class="px-3 py-2">{{ member.client_type }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Marital Status:</strong></td>
                            <td class="px-3 py-2">{{ member.marital_status }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Address:</strong></td>
                            <td class="px-3 py-2">{{ member.address }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Town:</strong></td>
                            <td class="px-3 py-2">{{ member.town }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Profession:</strong></td>
                            <td class="px-3 py-2">{{ member.profession }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Spouse Name:</strong></td>
                            <td class="px-3 py-2">{{ member.spouse_name }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Spouse Address:</strong></td>
                            <td class="px-3 py-2">{{ member.spouse_address }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Updated At:</strong></td>
                            <td class="px-3 py-2">{{ member.updated_at|date:"F d, Y H:i" }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <!-- Financial Details Card -->
            <div class="bg-white shadow-md rounded-lg p-4"> <!-- Adjusted p-4 for smaller padding -->
                <h2 class="text-lg font-semibold mb-2">Financial Details</h2>
                <table class="min-w-full divide-y divide-gray-200">
                    <tbody class="bg-white divide-y divide-gray-200">
                  
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Savings Amount:</strong></td>
                            <td class="px-3 py-2">Ksh {{ member.memberaccount.savings|intcomma }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Share Capital Amount:</strong></td>
                            <td class="px-3 py-2">Ksh {{ member.memberaccount.share_capital|intcomma }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Employment Status:</strong></td>
                            <td class="px-3 py-2">{{ member.employment_status }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Employment Income:</strong></td>
                            <td class="px-3 py-2">Ksh {{ member.employment_income|intcomma }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Total Loans Taken:</strong></td>
                            <td class="px-3 py-2">Ksh {{ total_loans_taken|intcomma }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Active Loan Principal:</strong></td>
                            <td class="px-3 py-2">Ksh {{ active_loan_principal|intcomma }}</td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2 whitespace-nowrap"><strong>Active Loan Balance:</strong></td>
                            <td class="px-3 py-2">Ksh {{ active_loan_balance|intcomma }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Back to Members Button -->
        <div class="text-center mt-6"> <!-- Adjusted mt-6 for smaller margin top -->
            <a href="{% url 'members:view_members' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Back to Members
            </a>
        </div>
    </div>
{% endblock %}

members/templates/transfer.html
{% extends 'base.html' %}

{% block title %}
    Transfer - AKIBANIPESA
{% endblock %}

{% block content %}
    {% include 'more_menu_members.html' %}
    <div class="container mx-auto mt-8 px-4">
        <!-- Message display section -->
        {% if messages %}
            <div class="container mt-4">
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <h1 class="text-2xl font-bold mb-4">Transfer from {{ member.first_name }} {{ member.last_name }}</h1>
        <form method="POST" class="max-w-md bg-white shadow-md rounded-lg p-6 mx-auto mb-4">
            {% csrf_token %}
            <div class="mb-4">
                <label for="transfer_from_account_type" class="block text-sm font-medium text-gray-700">Transfer from Account Type</label>
                <select class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" id="transfer_from_account_type" name="transfer_from_account_type">
                    <option value="savings">Savings</option>
                    <option value="share_capital">Share Capital</option>
                    
                </select>
            </div>
            <div class="mb-4">
                <label for="transfer_to_account_type" class="block text-sm font-medium text-gray-700">Transfer to Account Type</label>
                <select class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" id="transfer_to_account_type" name="transfer_to_account_type">
                    <option value="savings">Savings</option>
                    <option value="share_capital">Share Capital</option>
                    <option value="loan">Loan Repayment</option>
                </select>
            </div>
            <div class="mb-4">
                <label for="recipient_id" class="block text-sm font-medium text-gray-700">Recipient ID</label>
                <input type="text" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" id="recipient_id" name="recipient_id" style="max-width: 300px;">
            </div>
            <div class="mb-4">
                <label for="amount" class="block text-sm font-medium text-gray-700">Amount</label>
                <input type="text" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" id="amount" name="amount" style="max-width: 300px;">
            </div>
            <button type="submit" class="inline-block bg-blue-500 text-white px-4 py-2 rounded-md cursor-pointer hover:bg-blue-700">Transfer</button>
        </form>
    </div>
{% endblock %}

members/templates/view_members.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
    View Members - AKIBANIPESA
{% endblock %}

{% block content %}
    {% include 'more_menu_members.html' %}

    <div class="container mt-4">
        <h1 class="text-2xl font-bold mb-4">View Members</h1>
        
        <!-- Search Form -->
        <form method="get" action="{% url 'members:view_members' %}">
            <div class="row justify-content-center mb-4">
                <div class="col-md-6">
                    <input type="text" name="q" id="searchInput" placeholder="Search for members..." class="form-control" value="{{ query }}">
                </div>
                <div class="col-md-2">
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </div>
        </form>

        <div class="table-responsive">
            <table class="table table-bordered table-hover" id="membersTable">
                <thead class="thead-light">
                    <tr>
                        <th>Member ID</th>
                        <th>Name</th>
                        <th>Phone Number</th>
                        <th>Email</th>
                        <th>Loan Amount</th>
                        <th>Savings Amount</th>
                        <th>Share Capital Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for member in members %}
                    <tr onclick="window.location='{% url 'members:member_profile' member.id %}'" style="cursor: pointer;">
                        <td>{{ member.id }}</td>
                        <td>{{ member.first_name }} {{ member.last_name }}</td>
                        <td>{{ member.phone_number }}</td>
                        <td>{{ member.email }}</td>
                        <td>{{ member_loan_data|get_item:member.id|default:"0" }}</td>
                        <td>{{ member.memberaccount.savings|intcomma }}</td>
                        <td>{{ member.memberaccount.share_capital|intcomma }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="7">No members found.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}