loans/urls.py
from django.urls import path
from . import views

app_name = 'loans'

urlpatterns = [
    path('create-loan-product/', views.create_loan_product, name='create_loan_product'),
    path('search-member/', views.search_member_or_entity, name='search_member'),
    path('search-member/', views.search_member_or_entity, name='search_member_or_entity'),
    path('member-details/<int:member_id>/', views.member_details, name='member_details'),
    path('entity-details/<str:entity_id>/', views.entity_details, name='entity_details'),
    path('start-application/member/<int:member_id>/', views.start_application_member, name='start_application_member'),
    path('start-application/entity/<str:entity_id>/', views.start_application_entity, name='start_application_entity'),
    #path('loan-eligibility/<int:member_id>/', views.loan_eligibility, name='loan_eligibility'),
    path('start-application/member/<int:member_id>/', views.loan_eligibility_member, name='loan_eligibility_member'),
    path('start-application/entity/<str:entity_id>/', views.loan_eligibility_entity, name='loan_eligibility_entity'),
    path('loan-details/<int:member_id>/', views.loan_details_member, name='loan_details_member'),
    path('loan-details/<str:entity_id>/', views.loan_details_entity, name='loan_details_entity'),
    path('collaterals/<int:member_id>/<int:loan_id>/', views.collaterals, name='collaterals'),
    path('collaterals-entity/<str:entity_id>/<int:loan_id>/', views.collaterals_entity, name='collaterals_entity'),
    path('release-loan/<int:member_id>/<int:loan_id>/', views.release_loan, name='release_loan'),
    path('release-loan-entity/<str:entity_id>/<int:loan_id>/', views.release_loan_entity, name='release_loan_entity'),
    path('loan-summary/<int:member_id>/<int:loan_id>/', views.loan_summary, name='loan_summary'),
    path('loan-summary-entity/<str:entity_id>/<int:loan_id>/', views.loan_summary_entity, name='loan_summary_entity'),
    path('view-loan-products/',views. view_loan_products, name='view_loan_products'),
    path('view-issued-loans/',views. view_issued_loans, name='view_issued_loans'),
    #path('loan-eligibility/<int:member_id>/', views.loan_eligibility, name='loan_eligibility'),
    #path('collaterals/<int:member_id>/<int:loan_id>/', views.collaterals, name='collaterals'),
    path('guarantors/<int:member_id>/<int:loan_id>/', views.guarantors, name='guarantors'),
    path('guarantors_entity/<str:entity_id>/<int:loan_id>/', views.guarantors_entity, name='guarantors_entity'),
     # Other URL patterns...
    path('delete-guarantor/<int:member_id>/<int:loan_id>/<int:guarantor_id>/', views.delete_guarantor, name='delete_guarantor'),
    path('delete-collateral/<int:member_id>/<int:loan_id>/<int:collateral_id>/', views.delete_collateral, name='delete_collateral'),
    path('delete-guarantor-entity/<str:entity_id>/<int:loan_id>/<int:guarantor_id>/', views.delete_guarantor_entity, name='delete_guarantor_entity'),
    path('delete-collateral-entity/<str:entity_id>/<int:loan_id>/<int:collateral_id>/', views.delete_collateral_entity, name='delete_collateral_entity'),
    path('collateral-and-guarantor-check/<int:member_id>/<int:loan_id>/', views.collateral_and_guarantor_check, name='collateral_and_guarantor_check'),
    path('collateral-and-guarantor-check-entity/<str:entity_id>/<int:loan_id>/', views.collateral_and_guarantor_check_entity, name='collateral_and_guarantor_check_entity'),
    path('loan-approvals/', views.loan_approval_list, name='loan_approval_list'),
    #path('loan-approval/<int:loan_id>/', views.loan_approval_detail, name='loan_approval_detail'),
    path('loan-approval/member/<int:loan_id>/', views.loan_approval_member_detail, name='loan_approval_member_detail'),
    path('loan-approval/entity/<int:loan_id>/', views.loan_approval_entity_detail, name='loan_approval_entity_detail'),


]

saccomis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('sms/', include('sms.urls')),
    path('loans/', include('loans.urls')),
    path('reports/', include('reports.urls')),
    path('groups/', include('groups.urls')),
    path('accounting/', include('accounting.urls')),
    path('registry/', include('registry.urls')),
    path('', include('members.urls', namespace='members')),
]

sms/urls.py
# urls.py in the sms app

from django.urls import path
from . import views

app_name = 'sms'

urlpatterns = [
    path('compose/', views.compose_sms, name='compose_sms'),
    path('view/', views.view_sms, name='view_sms'),
]

loans/forms.py
# loans/forms.py
from django import forms
from .models import LoanProduct, IssuedLoan
from django import forms
from .models import Collateral, Guarantor
from members.models import Member


class LoanProductForm(forms.ModelForm):
    class Meta:
        model = LoanProduct
        fields = '__all__'


class LoanEligibilityForm(forms.Form):
    loan_product = forms.ModelChoiceField(queryset=LoanProduct.objects.all(), label='Loan Product')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['loan_product'].label_from_instance = lambda obj: obj.name


class IssueLoanForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['loan_product'].label_from_instance = lambda obj: obj.name

    class Meta:
        model = IssuedLoan
        fields = ['loan_product', 'loan_amount', 'repayment_period', 'loan_purpose', 'grace_period', 'repayments_start_date']


class CollateralForm(forms.ModelForm):
    class Meta:
        model = Collateral
        fields = ['collateral_type', 'document_ref_no', 'value']
    

class GuarantorForm(forms.ModelForm):
    guarantor_id = forms.IntegerField(label="Guarantor ID")

    class Meta:
        model = Guarantor
        fields = ['guarantor_id', 'guarantee_amount', 'loan_status']

class LoanApprovalForm(forms.ModelForm):
    class Meta:
        model = IssuedLoan
        fields = ['loan_status', 'comments']
        widgets = {
            'status': forms.Select(choices=IssuedLoan.LOAN_STATUSES),
            'comments': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
        }

        
class MemberSearchForm(forms.Form):
    member_id = forms.CharField(max_length=20)

loans/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import LoanProduct, IssuedLoan, Collateral, Guarantor
from .forms import LoanProductForm, MemberSearchForm, IssueLoanForm, CollateralForm, LoanEligibilityForm, CollateralForm, GuarantorForm
from groups.models import Entity, EntityAccount, EntityAccountsLedger  # Assuming you have an Entity model
import datetime
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.utils import timezone
from .utils import generate_unique_loan_ref_id
from django.conf import settings  # for getting the user model
from sms.utils import send_notification  # Import the send_notification function
from django.db.models import F
from datetime import timedelta
from decimal import Decimal, getcontext

# Set precision for Decimal calculations
getcontext().prec = 28

@login_required
def search_member_or_entity(request):
    member = None
    entity = None
    savings_amount = 0
    loan_amount = 0
    guaranteed_amount = 0

    if request.method == 'POST':
        form = MemberSearchForm(request.POST)
        if form.is_valid():
            member_or_entity_id = form.cleaned_data['member_id']
            if member_or_entity_id.isdigit():
                try:
                    member = Member.objects.get(id=int(member_or_entity_id))
                    account = MemberAccount.objects.get(member=member)
                    savings_amount = account.savings
                    #loan_amount = account.loan
                    guaranteed_amount = Guarantor.objects.filter(guarantor=member).aggregate(total=Sum('guarantee_amount'))['total'] or 0
                except Member.DoesNotExist:
                    messages.warning(request, f"Member not found matching '{member_or_entity_id}'.")
            else:
                try:
                    entity = Entity.objects.get(id=member_or_entity_id)
                    entity_account = EntityAccount.objects.get(entity=entity)
                    savings_amount = entity_account.savings
                    #loan_amount = entity_account.loan
                except Entity.DoesNotExist:
                    messages.warning(request, f"Entity not found matching '{member_or_entity_id}'.")

    else:
        form = MemberSearchForm()

    context = {
        'form': form,
        'member': member,
        'entity': entity,
        'savings_amount': savings_amount,
        'loan_amount': loan_amount,
        'guaranteed_amount': guaranteed_amount,
    }
    return render(request, 'loans/search_member_or_entity.html', context)


@login_required
def member_details(request, member_id):
    member = get_object_or_404(Member, id=member_id)
    account = get_object_or_404(MemberAccount, member=member)
    savings_amount = account.savings
    loan_amount = account.loan
    guaranteed_amount = Guarantor.objects.filter(guarantor=member).aggregate(total=Sum('guarantee_amount'))['total'] or 0
    context = {
        'member': member,
        'savings_amount': savings_amount,
        'loan_amount': loan_amount,
        'guaranteed_amount': guaranteed_amount,
    }
    return render(request, 'loans/member_details.html', context)

@login_required
def entity_details(request, entity_id):
    entity = get_object_or_404(Entity, id=entity_id)
    entity_account = get_object_or_404(EntityAccount, entity=entity)
    context = {
        'entity': entity,
        'entity_account': entity_account,
    }
    return render(request, 'loans/entity_details.html', context)

@login_required
def start_application_member(request, member_id):
    member = get_object_or_404(Member, id=member_id)
    return render(request, 'loans/start_application_member.html', {'member': member})

@login_required
def start_application_entity(request, entity_id):
    entity = get_object_or_404(Entity, id=entity_id)
    return render(request, 'loans/start_application_entity.html', {'entity': entity})
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from decimal import Decimal
from members.models import Member, MemberAccount, MemberAccountsLedger
from loans.models import IssuedLoan, Collateral, Guarantor
from accounting.models import SaccoCharge, SaccoAccountsLedger, SaccoAccount
from .forms import IssueLoanForm
from .utils import generate_unique_loan_ref_id
from datetime import timedelta
from django.db.models import Sum

@login_required
def loan_details_member(request, member_id):
    member = get_object_or_404(Member, id=member_id)
    member_account = get_object_or_404(MemberAccount, member=member)

    if request.method == 'POST':
        form = IssueLoanForm(request.POST)
        if form.is_valid():
            loan = form.save(commit=False)
            loan.content_type = ContentType.objects.get_for_model(member)
            loan.object_id = member.id

            loan_amount = form.cleaned_data['loan_amount']
            repayment_period = form.cleaned_data['repayment_period']

            # Fetch SACCO charges
            loan_interest = SaccoCharge.objects.get(charge_name='loan_interest')
            loan_charge_un_100000 = SaccoCharge.objects.get(charge_name='loan_charge_un_100000')
            loan_charge_ov_100000 = SaccoCharge.objects.get(charge_name='loan_charge_ov_100000')
            loan_boost_charge = SaccoCharge.objects.get(charge_name='loan_boost_charge')
            loan_top_up_charge = SaccoCharge.objects.get(charge_name='loan_top_up_charge')

            # Calculate interest
            interest_rate = loan_interest.charge_value / 100
            months = Decimal(repayment_period)
            numerator = loan_amount * interest_rate * (1 + interest_rate) ** months
            denominator = (1 + interest_rate) ** months - 1
            installment_amount = numerator / denominator

            # Determine processing fee based on loan amount
            if loan_amount < 100000:
                processing_fee = loan_charge_un_100000.charge_value
            else:
                processing_fee = loan_charge_ov_100000.charge_value

            # Calculate loan boost charge if applicable
            six_months_ago = timezone.now() - timedelta(days=180)
            two_months_ago = timezone.now() - timedelta(days=60)

            last_six_months_savings = MemberAccountsLedger.objects.filter(
                member_id=member.id, tr_account='savings', updated_at__gte=six_months_ago
            ).order_by('-updated_at')[:6]

            last_two_months_savings = MemberAccountsLedger.objects.filter(
                member_id=member.id, tr_account='savings', updated_at__gte=two_months_ago
            ).order_by('-updated_at')[:2]

            if last_six_months_savings and last_two_months_savings:
                avg_savings_last_6 = sum(tx.tr_amount for tx in last_six_months_savings) / len(last_six_months_savings)
                avg_savings_last_2 = sum(tx.tr_amount for tx in last_two_months_savings) / len(last_two_months_savings)

                if avg_savings_last_2 > avg_savings_last_6 * 2:
                    boost_charge = loan_boost_charge.charge_value / 100 * avg_savings_last_2
                    processing_fee += boost_charge

            # Check for existing unsettled loans and apply top-up charge if applicable
            unsettled_loans = IssuedLoan.objects.filter(object_id=member_id, loan_status='active')
            remaining_loan_amount = loan_amount  # Initialize remaining_loan_amount to the full loan amount

            if unsettled_loans.exists():
                unsettled_loan_balance = unsettled_loans.aggregate(total_balance=Sum('loan_balance'))['total_balance']
                top_up_charge = loan_top_up_charge.charge_value / 100 * unsettled_loan_balance
                processing_fee += top_up_charge

                # Attempt to settle existing loans
                for unsettled_loan in unsettled_loans:
                    loan_balance = unsettled_loan.loan_balance
                    if remaining_loan_amount >= loan_balance:
                        remaining_loan_amount -= loan_balance
                        # Settle the loan
                        unsettled_loan.loan_balance = 0
                        unsettled_loan.loan_status = 'settled'
                        unsettled_loan.save()

                        # Record the loan repayment in MemberAccountsLedger
                        MemberAccountsLedger.objects.create(
                            member_id=member,
                            tr_amount=loan_balance,
                            external_ref_code=generate_unique_loan_ref_id(),
                            tr_type='credit',
                            tr_account='loan_repayment',
                            account_id=unsettled_loan.id,
                            tr_mode_id=1,  # Default to Mpesa for now
                            tr_origin='member_deposit',
                            tr_destn='member_account',
                            updated_by=request.user,
                            updated_at=timezone.now()
                        )

                        # Release collaterals and guarantors
                        Collateral.objects.filter(loan=unsettled_loan).update(loan_status='settled')
                        Guarantor.objects.filter(loan=unsettled_loan).update(loan_status='settled')
                    else:
                        # Not enough loan amount to settle the loan
                        return render(request, 'loans/loan_eligibility_summary.html', {
                            'member': member,
                            'loan_amount': loan_amount,
                            'eligibility_results': {'qualified': False, 'reason': 'You must settle the existing loan first, maybe apply for a bigger loan.'},
                        })

loans/templates/loans/collateral_and_guarantor_check.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto mt-8 px-4">
    <h2 class="text-2xl font-bold mb-4">Collateral and Guarantor Check</h2>

    {% if is_sufficient %}
        <div class="alert alert-success mb-4">
            <p class="font-semibold">Check Successful</p>
            <p>The collateral and guarantor value ({{ total_value }}) is equal to or exceeds the loan amount ({{ required_value }}).</p>
            <p>You can proceed to release the loan.</p>
        </div>
        <a href="{% url 'loans:loan_approval_list'  %}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-md inline-block mb-4">Next</a>
    {% else %}
        <div class="alert alert-danger mb-4">
            <p class="font-semibold">Check Failed</p>
            <p>The total value of the collaterals and guarantors ({{ total_value }}) does not cover the loan amount ({{ required_value }}).</p>
            <p>Please add more collaterals or guarantors to cover the loan amount.</p>

            {% if insufficient_guarantors %}
                <h3>Guarantors with Insufficient Free Savings</h3>
                <ul class="mb-2">
                    {% for item in insufficient_guarantors %}
                        <li>Guarantor: {{ item.guarantor.first_name }} - Guarantee Amount: {{ item.guarantee_amount }} exceeds Free Savings: {{ item.free_savings }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <a href="{% url 'loans:collaterals' member.id loan.id %}" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded-md inline-block mb-2 mr-2">Back to Collaterals</a>
        <a href="{% url 'loans:guarantors' member.id loan.id %}" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded-md inline-block mb-2">Back to Guarantors</a>
    {% endif %}

    <h3 class="text-lg font-semibold mb-2">Collaterals</h3>
    <ul class="mb-4">
        {% for collateral in collaterals %}
            <li class="mb-2">
                {{ collateral.collateral_type }}: {{ collateral.value }}
                <a href="{% url 'loans:delete_collateral' member.id loan.id collateral.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded-md ml-2">[X]</a>
            </li>
        {% endfor %}
    </ul>

    <h3 class="text-lg font-semibold mb-2">Guarantors</h3>
    <ul>
        {% for guarantor in guarantors %}
            <li class="mb-2">
                {{ guarantor.guarantor.first_name }} {{ guarantor.guarantor.last_name }}: {{ guarantor.guarantee_amount }}
                <a href="{% url 'loans:delete_guarantor' member.id loan.id guarantor.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded-md ml-2">[X]</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

loans/templates/loans/collateral_and_guarantor_check_entity.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto mt-8 px-4">
    <h2 class="text-2xl font-bold mb-4">Collateral and Guarantor Check</h2>

    {% if is_sufficient %}
        <div class="alert alert-success mb-4">
            <p class="font-semibold">Check Successful</p>
            <p>The collateral and guarantor value ({{ total_value }}) is equal to or exceeds the loan amount ({{ required_value }}).</p>
            <p>You can proceed to release the loan.</p>
        </div>
        <a href="{% url 'loans:loan_approval_list' %}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-md inline-block mb-4">Next</a>
    {% else %}
        <div class="alert alert-danger mb-4">
            <p class="font-semibold">Check Failed</p>
            <p>The total value of the collaterals and guarantors ({{ total_value }}) does not cover the loan amount ({{ required_value }}).</p>
            <p>Please add more collaterals or guarantors to cover the loan amount.</p>

            {% if insufficient_guarantors %}
                <h3>Guarantors with Insufficient Free Savings</h3>
                <ul class="mb-2">
                    {% for item in insufficient_guarantors %}
                        <li>Guarantor: {{ item.guarantor.first_name }} - Guarantee Amount: {{ item.guarantee_amount }} exceeds Free Savings: {{ item.free_savings }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <a href="{% url 'loans:collaterals_entity' entity.id loan.id %}" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded-md inline-block mb-2 mr-2">Back to Collaterals</a>
        <a href="{% url 'loans:guarantors_entity' entity.id loan.id %}" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded-md inline-block mb-2">Back to Guarantors</a>
    {% endif %}

    <h3 class="text-lg font-semibold mb-2">Collaterals</h3>
    <ul class="mb-4">
        {% for collateral in collaterals %}
            <li class="mb-2">
                {{ collateral.collateral_type }}: {{ collateral.value }}
                <a href="{% url 'loans:delete_collateral_entity' entity.id loan.id collateral.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded-md ml-2">[X]</a>
            </li>
        {% endfor %}
    </ul>

    <h3 class="text-lg font-semibold mb-2">Guarantors</h3>
    <ul>
        {% for guarantor in guarantors %}
            <li class="mb-2">
                {{ guarantor.guarantor.first_name }} {{ guarantor.guarantor.last_name }}: {{ guarantor.guarantee_amount }}
                <a href="{% url 'loans:delete_guarantor_entity' entity.id loan.id guarantor.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded-md ml-2">[X]</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

loans/templates/loans/guarantors.html
{% extends "base.html" %}
{% block content %}
<div class="container mx-auto mt-8 px-4">
    <h2 class="text-2xl font-bold mb-4">Add Guarantor for {{ member.first_name }} {{ member.last_name }}'s Loan</h2>
    
    <!-- Message display section -->
    {% if messages %}
    <div class="mb-4">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags|default:'info' }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <form method="post" class="max-w-md bg-white shadow-md rounded-lg p-6 mx-auto mb-4">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md mt-4 inline-block">Add Guarantor</button>
    </form>

    <h3 class="text-lg font-semibold mb-2">Existing Guarantors</h3>
    <ul class="mb-4">
        {% for guarantor in guarantors %}
        <li class="mb-2">
            <span class="text-gray-700">{{ guarantor.guarantor.first_name }} {{ guarantor.guarantor.last_name }}: Ksh {{ guarantor.guarantee_amount }} - {{ guarantor.loan_status }}</span>
            <a href="{% url 'loans:delete_guarantor' member.id loan.id guarantor.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded-md ml-2">[X]</a>
        </li>
        {% endfor %}
    </ul>
    <button onclick="window.location.href='{% url 'loans:collateral_and_guarantor_check' member.id loan.id %}'" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md">Next</button>
</div>
{% endblock %}

loans/templates/loans/guarantors_entity.html
{% extends "base.html" %}
{% block content %}
<div class="container mx-auto mt-8 px-4">
    <h2 class="text-2xl font-bold mb-4">Add Guarantor for {{ entity.entity_name }}'s Loan</h2>
    
    <!-- Message display section -->
    {% if messages %}
    <div class="mb-4">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags|default:'info' }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <form method="post" class="max-w-md bg-white shadow-md rounded-lg p-6 mx-auto mb-4">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md mt-4 inline-block">Add Guarantor</button>
    </form>

    <h3 class="text-lg font-semibold mb-2">Existing Guarantors</h3>
    <ul class="mb-4">
        {% for guarantor in guarantors %}
        <li class="mb-2">
            <span class="text-gray-700">{{ guarantor.guarantor.first_name }} {{ guarantor.guarantor.last_name }}: Ksh {{ guarantor.guarantee_amount }} - {{ guarantor.loan_status }}</span>
            <a href="{% url 'loans:delete_guarantor_entity' entity.id loan.id guarantor.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded-md ml-2">[X]</a>
        </li>
        {% endfor %}
    </ul>
    <button onclick="window.location.href='{% url 'loans:collateral_and_guarantor_check_entity' entity.id loan.id %}'" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md">Next</button>
</div>
{% endblock %}

loans/templates/loans/loan_eligibility_member.html
{% extends 'base.html' %}

{% block title %}
    Loan Eligibility Summary - AKIBANIPESA
{% endblock %}

{% block content %}
    <div class="container mx-auto mt-8 px-4">
        <h1 class="text-2xl font-bold mb-4">Loan Eligibility Summary</h1>
        <p>Member ID: {{ member.id }}</p>
        <p>Member Name: {{ member.first_name }} {{ member.last_name }}</p>
        
        {% if eligibility_results.qualified %}
            <p class="text-green-500 font-semibold mt-4">Congratulations! You are eligible for the loan.</p>
            <!-- Add button to proceed to collaterals -->
            <a href="{% url 'loans:collaterals_member' member_id=member.id %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md mt-4 inline-block">Proceed to Collaterals</a>
        {% else %}
            <p class="text-red-500 font-semibold mt-4">Sorry, you are not eligible for the loan due to the following reasons:</p>
            <ul class="mt-2">
                {% for reason in eligibility_results.reasons %}
                    <li>{{ reason }}</li>
                {% endfor %}
            </ul>
            
            <!-- Add button to search for another member -->
            <a href="{% url 'loans:search_member_or_entity' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md mt-4 inline-block">Search Another Member</a>
        {% endif %}
    </div>
{% endblock %}

loans/templates/loans/loan_eligibility_summary.html
{% extends 'base.html' %}

{% block title %}
    Loan Eligibility Summary - AKIBANIPESA
{% endblock %}

{% block content %}
    <div class="container mx-auto mt-8 px-4">
        <h1 class="text-2xl font-bold mb-4">Loan Eligibility Summary</h1>
        <p>Member ID: {{ member.id }}</p>
        <p>Member Name: {{ member.first_name }} {{ member.last_name }}</p>
        <p>Loan Product: {{ loan_product }}</p>
        
        {% if eligibility_results.qualified %}
            <p class="text-green-500 font-semibold mt-4">Congratulations! You are eligible for the loan.</p>
            <!-- Add button to proceed to collaterals -->
            <a href="{% url 'loans:collaterals' member_id=member.id %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md mt-4 inline-block">Proceed to Collaterals</a>
        {% else %}
            <p class="text-red-500 font-semibold mt-4">Sorry, you are not eligible for the loan due to the following reasons:</p>
            <ul class="mt-2">
                {% for reason in eligibility_results.reasons %}
                    <li>{{ reason }}</li>
                {% endfor %}
            </ul>
            
            <!-- Add button to search for another member -->
            <a href="{% url 'loans:search_member' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md mt-4 inline-block">Search Another Member</a>
        {% endif %}
    </div>
{% endblock %}